name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy code via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.vitasoftsolutions.com
          username: vistock@vistock.vitasoftsolutions.com
          password: U70v(5gHHRo1;p
          server-dir: /home/vitasoft/vistock.vitasoftsolutions.com/vistock
